-
  id: "ncl"
  name: "Newcastle"
  timezone: "+00:00"
  service: "twitter"
  account: "@jonathan_worth"
  hashtag: "#openlab_hub"
  lang: "en"
-
  id: "coventry"
  name: "Coventry"
  timezone: "+00:00"
  service: "twitter"
  account: "@jonathan_worth"
  hashtag: "#coventry_hub"
  lang: "en"
-
  id: "brazil"
  name: "Brazil"
  timezone: "+00:00"
  service: "twitter"
  account: "@jonathan_worth"
  hashtag: "#brazil_hub"
  lang: "en"
