hashtag: "#cainterpretation"
starts: "2017-08-14T22:47:31-07:00"
ends: "2017-12-30T22:47:31-07:00"
accounts: 
  - tombartindale
langs:
  - en
about: about.md
info: info.md
slug: interpretation
classes:
  -
    dir: class1
    slug: interpretation
    content:
      -
        url: intro.md
        slug: intro
      -
        url: fourcorners.md
        slug: fourcorners
      -
        url: extra-pre-reading.md
        slug: prereading
      -
        url: homework.md
        slug: homework
      -
        url: class.md
        slug: liveclass
        schedule:
          -
            release_at: "2017-08-18T22:47:31-07:00"
            leadhub: true
            hub_id: "ncl"
          -
            release_at: "2017-08-18T22:47:31-07:00"
            hub_id: "coventry"
          -
            release_at: "2017-08-18T22:47:31-07:00"
            hub_id: "brazil"
      -
        url: deepdive.md
        slug: deepdive
      -
        url: extended.md
        slug: extended
      -
        url: homework1.md
        slug: homework1
      -
        url: whatnext.md
        slug: whatnext
